package com.example.demo.model;

public enum FileDealerCode {
    FILE_SAVE_SUCCESS,
    FILE_SAVE_FAILED,
    DATA_ASSET_SAVE_SUCCESS,
    DATA_ASSET_SAVE_FAILED,
    DATA_INFO_SAVE_SUCCESS,
    DATA_INFO_SAVE_FAILED,
    DATA_CONTENT_SAVE_SUCCESS,
    DATA_CONTENT_SAVE_FAILED,
}
